[pytest]
asyncio_mode = auto
testpaths = tests
addopts = --ignore=tests/e2e -n auto --dist worksteal -p no:cacheprovider
cache_dir = /tmp/.pytest_cache
filterwarnings =
	ignore::DeprecationWarning:passlib.utils
	ignore:cache could not write path .*:pytest.PytestCacheWarning
